[do_spaces]
access_key = "DO801N3QDNK4AXVXMWTA"
secret_key = "EDE+DHwD5IwsYJfJtJPJdcDKObwA1oo3LPWFvzmDgc0"
region = "fra1"
endpoint_url = "https://usedcars.fra1.digitaloceanspaces.com"
bucket_name = "usedcars"

[openai]
api_key = "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"

[langfuse]
public_key = "pk-lf-6cdd9b64-354a-4566-a6dd-4e6e0fb6f27e"
secret_key = "sk-lf-23ed99c4-5775-4b0e-a0a7-b5dafa801975"
host="https://cloud.langfuse.com"

[logfire]
token = "pylf_v1_us_WhwKMv46MrNGDZKJ4xYc2HTtGK2V1tX7m5B97Q2zrSYB"